"use client";

import { useMemo, useRef, useState } from "react";
import { AlertTriangle, Ban, Check, Download, Eye, FileText, PackageCheck, Pencil, Play, RotateCcw, Trash2, Upload, X } from "lucide-react";
import { demoInvoices } from "../../lib/invoices/demo";
import { processInvoiceQueue } from "../../lib/invoices/queue";
import type { ConfidenceLevel, ExtractionField, Invoice, InvoiceItem, UploadedDocument } from "../../lib/invoices/types";
import { exportInvoiceWorkbook } from "../../lib/excel/export-invoices";
import { reconcileDeliveries, reconciliationSummary } from "../../lib/invoices/reconcile";
import { splitDocumentBatches } from "../../lib/invoices/batch-state";

const money = (value: number) => new Intl.NumberFormat("es-CR", { style: "currency", currency: "CRC", maximumFractionDigits: 0 }).format(value).replace("CRC", "₡");
const size = (bytes: number) => bytes < 1_000_000 ? (bytes / 1000).toFixed(0) + " KB" : (bytes / 1_000_000).toFixed(1) + " MB";
const tone = (value: string) => /Error|Baja/.test(value) ? "red" : /Requiere|Media|Cancelado/.test(value) ? "amber" : "green";
const cloneDemo = () => demoInvoices.map((invoice) => ({ ...invoice, id: crypto.randomUUID(), items: invoice.items.map((item) => ({ ...item, id: crypto.randomUUID() })), issues: invoice.issues.map((issue) => ({ ...issue, id: crypto.randomUUID() })) }));

export function InvoiceIntelligence({ notify, mode, initialInvoices = [], onInvoicesChange }: { notify: (message: string) => void; mode: "demo" | "real"; initialInvoices?: Invoice[]; onInvoicesChange?: (invoices: Invoice[]) => void }) {
  const initialBatches = useMemo(() => splitDocumentBatches(initialInvoices), [initialInvoices]);
  const [invoices, setInvoicesState] = useState<Invoice[]>(initialBatches.invoices);
  const [deliveryNotes, setDeliveryNotesState] = useState<Invoice[]>(initialBatches.deliveryNotes);
  const [fileEntries, setFileEntries] = useState<{ documentId: string; file: File }[]>([]);
  const [documents, setDocuments] = useState<UploadedDocument[]>([]);
  const [noteEntries, setNoteEntries] = useState<{ documentId: string; file: File }[]>([]);
  const [noteDocuments, setNoteDocuments] = useState<UploadedDocument[]>([]);
  const [concurrency, setConcurrency] = useState(3);
  const [invoiceRunning, setInvoiceRunning] = useState(false);
  const [noteRunning, setNoteRunning] = useState(false);
  const [reconciliation, setReconciliation] = useState<ReturnType<typeof reconcileDeliveries>>([]);
  const [view, setView] = useState<"Resultados" | "Requieren revisión">("Resultados");
  const [supplier, setSupplier] = useState("Todos los proveedores");
  const [selected, setSelected] = useState<Invoice | null>(null);
  const abortRef = useRef<AbortController | null>(null);
  const invoicesRef = useRef<Invoice[]>(initialBatches.invoices); const notesRef = useRef<Invoice[]>(initialBatches.deliveryNotes);
  const persist = (nextInvoices: Invoice[], nextNotes: Invoice[]) => onInvoicesChange?.([...nextInvoices, ...nextNotes]);
  const setInvoices = (value: Invoice[] | ((current: Invoice[]) => Invoice[])) => { const next = typeof value === "function" ? value(invoicesRef.current) : value; invoicesRef.current = next; setInvoicesState(next); persist(next, notesRef.current); };
  const setDeliveryNotes = (value: Invoice[] | ((current: Invoice[]) => Invoice[])) => { const next = typeof value === "function" ? value(notesRef.current) : value; notesRef.current = next; setDeliveryNotesState(next); persist(invoicesRef.current, next); };

  const update = (id: string, patch: Partial<Invoice>) => setInvoices((current) => current.map((invoice) => invoice.id === id ? { ...invoice, ...patch } : invoice));
  const updateDocument = (id: string, patch: Partial<UploadedDocument>) => setDocuments((current) => {
    const next = current.map((document) => document.id === id ? { ...document, ...patch } : document);
    const flattened = next.flatMap((document) => document.invoices).filter((document) => document.documentType !== "delivery_note");
    invoicesRef.current = flattened; setInvoicesState(flattened); persist(flattened, notesRef.current);
    return next;
  });
  const updateNoteDocument = (id: string, patch: Partial<UploadedDocument>) => setNoteDocuments((current) => {
    const next = current.map((document) => document.id === id ? { ...document, ...patch } : document);
    const flattened = next.flatMap((document) => document.invoices).map((document) => ({ ...document, documentType: "delivery_note" as const }));
    notesRef.current = flattened; setDeliveryNotesState(flattened); persist(invoicesRef.current, flattened); return next;
  });
  const chooseFiles = (list: FileList | null) => {
    if (!list) return; const selectedFiles = Array.from(list).filter((file) => file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf")).slice(0, 200);
    const entries = selectedFiles.map((file) => ({ documentId: crypto.randomUUID(), file }));
    setFileEntries(entries); setInvoices([]); setDocuments(entries.map(({ documentId, file }) => ({ id: documentId, fileName: file.name, fileSize: file.size, pageCount: 0, invoices: [], status: "Pendiente", progress: 0, progressLabel: "En espera", detectedInvoices: 0 }))); notify(selectedFiles.length + " PDFs seleccionados");
  };
  const chooseNotes = (list: FileList | null) => { if (!list) return; const selectedFiles = Array.from(list).filter((file) => file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf")).slice(0, 200); const entries = selectedFiles.map((file) => ({ documentId: crypto.randomUUID(), file })); setNoteEntries(entries); setNoteDocuments(entries.map(({ documentId, file }) => ({ id: documentId, fileName: file.name, fileSize: file.size, pageCount: 0, invoices: [], status: "Pendiente", progress: 0, progressLabel: "En espera", detectedInvoices: 0, batchType: "delivery_note" }))); notify(selectedFiles.length + " PDFs de notas seleccionados"); };
  const start = async () => {
    if (!fileEntries.length || invoiceRunning) return; setInvoiceRunning(true); const controller = new AbortController(); abortRef.current = controller;
    await processInvoiceQueue(fileEntries.map((entry) => entry.file), fileEntries.map((entry) => entry.documentId), concurrency, controller.signal, updateDocument); setInvoiceRunning(false); notify(controller.signal.aborted ? "Procesamiento cancelado" : "Lote analizado");
  };
  const retry = async (invoice: Invoice) => {
    const entry = fileEntries.find((candidate) => candidate.documentId === invoice.sourceDocumentId); if (!entry) { notify("El archivo original ya no está disponible; selecciónalo nuevamente"); return; }
    const controller = new AbortController(); await processInvoiceQueue([entry.file], [entry.documentId], 1, controller.signal, updateDocument);
  };
  const processNotes = async () => { if (!noteEntries.length || noteRunning) return; setNoteRunning(true); const controller = new AbortController(); abortRef.current = controller; await processInvoiceQueue(noteEntries.map((entry) => entry.file), noteEntries.map((entry) => entry.documentId), concurrency, controller.signal, updateNoteDocument, "delivery_note"); setNoteRunning(false); notify("Notas de entrega analizadas"); };
  const suppliers = useMemo(() => [...new Set(invoices.map((invoice) => invoice.supplier.normalizedValue).filter(Boolean) as string[])], [invoices]);
  const visible = invoices.filter((invoice) => (supplier === "Todos los proveedores" || invoice.supplier.normalizedValue === supplier) && (view === "Resultados" || invoice.status === "Requiere revisión"));
  const completed = visible.filter((invoice) => invoice.status === "Completado").length;
  const reviews = visible.filter((invoice) => invoice.status === "Requiere revisión").length;
  const errors = visible.filter((invoice) => invoice.status === "Error").length;
  const total = visible.reduce((sum, invoice) => sum + (invoice.total.normalizedValue ?? 0), 0);
  const productCount = visible.reduce((sum, invoice) => sum + invoice.items.length, 0);
  const units = visible.flatMap((invoice) => invoice.items).reduce((sum, item) => sum + (item.quantity.normalizedValue ?? 0), 0);
  const reconciliationKpis = useMemo(() => reconciliationSummary(reconciliation), [reconciliation]);
  const executeReconciliation = () => { if (!invoices.length || !deliveryNotes.length) { notify("Debe procesar facturas y notas de entrega antes de ejecutar la conciliación."); return; } setReconciliation(reconcileDeliveries([...invoices, ...deliveryNotes])); notify("Conciliación ejecutada"); };

  return <div className="invoice-intelligence">
    <div className="invoice-hero"><div><span className="eyebrow">INVOICE INTELLIGENCE · {mode === "demo" ? "DEMO" : "DATOS REALES"}</span><h2>Analizar facturas</h2><p>Convierte facturas PDF en datos revisables y un Excel consolidado. Los documentos permanecen en este dispositivo.</p></div><div className="button-row"><button className="secondary" onClick={() => { setInvoices(cloneDemo()); setFileEntries([]); setDocuments([]); notify("Ejemplo cargado en el entorno actual"); }}><Play size={16}/> Cargar ejemplo</button></div></div>
    <div className="privacy-note"><Check size={16}/><span><b>Procesamiento local</b> Los PDFs no se suben a servidores ni se guardan en localStorage.</span></div>
    <div className="queue-toolbar"><div><b>Facturas</b><span>{fileEntries.length} archivo(s) · {documents.reduce((sum, document) => sum + document.pageCount, 0)} páginas · {invoices.length} facturas detectadas</span></div><label className="primary file-button"><Upload size={16}/> Cargar facturas<input type="file" accept="application/pdf,.pdf" multiple onChange={(event) => chooseFiles(event.target.files)}/></label>{invoiceRunning ? <button className="secondary danger" onClick={() => abortRef.current?.abort()}><Ban size={15}/> Cancelar</button> : <button className="primary" disabled={!fileEntries.length} onClick={start}>Iniciar análisis</button>}<button className="secondary" disabled={!fileEntries.length && !invoices.length} onClick={() => { setFileEntries([]); setDocuments([]); setInvoices([]); setReconciliation([]); }}>Limpiar facturas</button></div>
    <div className="queue-toolbar"><div><b>Notas de Entrega</b><span>{noteEntries.length} archivo(s) · {noteDocuments.reduce((sum, document) => sum + document.pageCount, 0)} páginas · {deliveryNotes.length} notas detectadas</span></div><label className="secondary file-button"><Upload size={16}/> Cargar notas<input type="file" accept="application/pdf,.pdf" multiple onChange={(event) => chooseNotes(event.target.files)}/></label>{noteRunning ? <button className="secondary danger" onClick={() => abortRef.current?.abort()}><Ban size={15}/> Cancelar</button> : <button className="primary" disabled={!noteEntries.length} onClick={processNotes}>Procesar notas</button>}<button className="secondary" disabled={!noteEntries.length && !deliveryNotes.length} onClick={() => { setNoteEntries([]); setNoteDocuments([]); setDeliveryNotes([]); setReconciliation([]); }}>Limpiar notas</button></div>
    {noteDocuments.length > 0 && <div className="invoice-table-wrap"><table><thead><tr><th>Nota cargada</th><th>Página actual</th><th>OCR</th><th>Notas detectadas</th><th>Estado</th><th>Progreso</th></tr></thead><tbody>{noteDocuments.map((document) => <tr key={document.id}><td>{document.fileName}</td><td>{document.currentPage ? `Página ${document.currentPage} / ${document.pageCount}` : "—"}</td><td>{document.ocrProgress == null ? "No requerido" : `${document.ocrProgress}%`}</td><td>{document.detectedInvoices}</td><td>{document.status}</td><td>{document.progress}%</td></tr>)}</tbody></table></div>}
    <div className="queue-toolbar"><div><b>Conciliación documental</b><span>Utiliza exclusivamente los resultados separados de facturas y notas.</span></div><button className="primary" onClick={executeReconciliation}>Ejecutar conciliación</button><button className="secondary" onClick={() => exportInvoiceWorkbook([...invoices, ...deliveryNotes])} disabled={!invoices.length && !deliveryNotes.length}><Download size={15}/> Exportar Excel</button></div>
    {reconciliation.length > 0 && <><div className="invoice-kpis"><MiniKpi label="Coinciden" value={String(reconciliationKpis.matches)}/><MiniKpi label="Facturas sin nota" value={String(reconciliationKpis.invoicesWithoutNote)} tone="amber"/><MiniKpi label="Notas sin factura" value={String(reconciliationKpis.notesWithoutInvoice)} tone="amber"/><MiniKpi label="Duplicados" value={String(reconciliationKpis.duplicates)} tone="red"/><MiniKpi label="Revisión" value={String(reconciliationKpis.review)} tone="red"/><MiniKpi label="Conciliado" value={`${reconciliationKpis.percentage.toFixed(1)}%`}/></div><div className="invoice-table-wrap"><table><thead><tr><th>Entrega</th><th>Factura</th><th>Fecha factura</th><th>Nota entrega</th><th>Pedido</th><th>Orden compra</th><th>Estado</th><th>Observación</th></tr></thead><tbody>{reconciliation.map((record) => { const invoice = record.invoices[0]; const note = record.deliveryNotes[0]; return <tr key={record.id}><td className="strong">{record.deliveryNumber || "—"}</td><td>{invoice?.invoiceNumber.normalizedValue || "—"}</td><td>{invoice?.date.normalizedValue || "—"}</td><td>{note?.deliveryNumber?.normalizedValue || "—"}</td><td>{invoice?.orderNumber?.normalizedValue || note?.orderNumber?.normalizedValue || "—"}</td><td>{invoice?.purchaseOrder.normalizedValue || note?.purchaseOrder.normalizedValue || "—"}</td><td><span className={"badge " + tone(record.status)}>{record.status}</span></td><td>{record.observation}</td></tr>; })}</tbody></table></div></>}
    <div className="queue-toolbar"><div><b>Configuración de procesamiento</b><span>La concurrencia se aplica al lote que se procese.</span></div><label>Procesar simultáneamente <select value={concurrency} onChange={(event) => setConcurrency(Number(event.target.value))}>{[1,2,3,4,5].map((value) => <option key={value}>{value}</option>)}</select></label></div>
    {documents.length > 0 && <div className="invoice-table-wrap"><table><thead><tr><th>Documento</th><th>Página actual</th><th>OCR de la página</th><th>Facturas detectadas</th><th>Estado</th><th>Progreso total</th></tr></thead><tbody>{documents.map((document) => <tr key={document.id}><td className="strong">{document.fileName}<small className="sub">{size(document.fileSize)}</small></td><td className="strong">{document.currentPage ? `Página ${document.currentPage} / ${document.pageCount}` : document.pageCount ? `— / ${document.pageCount}` : "—"}<small className="sub">{document.status === "Procesando" && document.currentPage ? `Procesando: página ${document.currentPage}` : document.progressLabel}</small></td><td>{document.ocrProgress == null ? "No requerido" : `OCR ${document.ocrProgress}%`}</td><td>{document.detectedInvoices} facturas detectadas</td><td><span className={"badge " + tone(document.status)}>{document.status}</span></td><td><div className="invoice-progress"><i style={{ width: document.progress + "%" }}/><small>{document.progress}%</small></div></td></tr>)}</tbody></table></div>}
    {invoices.length === 0 ? <div className="invoice-empty"><FileText/><h3>{documents.length ? "Documentos listos para analizar" : "Selecciona hasta 200 documentos PDF"}</h3><p>Un documento puede contener una o muchas facturas. SYNERA procesa las páginas de forma aislada.</p><div><span>PDF con texto</span><span>Factura escaneada</span><span>Varias facturas</span></div></div> : <>
      <div className="invoice-kpis"><MiniKpi label="Facturas listas" value={String(completed)} /><MiniKpi label="Requieren revisión" value={String(reviews)} tone="amber"/><MiniKpi label="Con error" value={String(errors)} tone="red"/><MiniKpi label="Total de compra" value={money(total)}/><MiniKpi label="Productos" value={productCount.toLocaleString("es-CR")}/><MiniKpi label="Unidades" value={units.toLocaleString("es-CR")}/><MiniKpi label="Proveedores" value={String(suppliers.length)}/></div>
      <div className="invoice-tabs"><button className={view === "Resultados" ? "active" : ""} onClick={() => setView("Resultados")}>Resultados</button><button className={view === "Requieren revisión" ? "active" : ""} onClick={() => setView("Requieren revisión")}><AlertTriangle size={14}/> Requieren revisión <em>{reviews}</em></button><div/><select value={supplier} onChange={(event) => setSupplier(event.target.value)}><option>Todos los proveedores</option>{suppliers.map((name) => <option key={name}>{name}</option>)}</select><button className="primary" onClick={() => exportInvoiceWorkbook(visible)} disabled={!visible.length}><Download size={15}/> Exportar Excel</button></div>
      {view === "Requieren revisión" ? <div className="review-grid">{visible.map((invoice) => <article className="review-card" key={invoice.id}><div><AlertTriangle/><span><b>{invoice.fileName}</b><small>Página {invoice.sourcePageStart ?? "—"} · {invoice.invoiceNumber.normalizedValue || "Factura sin identificar"} · {invoice.supplier.normalizedValue || "Proveedor no identificado"}</small></span></div><ul>{invoice.issues.filter((issue) => !issue.resolved).map((issue) => <li key={issue.id}>{issue.problem}</li>)}</ul><button className="secondary" onClick={() => setSelected(invoice)}>Revisar</button></article>)}</div> : <div className="invoice-table-wrap"><table><thead><tr><th>Estado</th><th>Archivo</th><th>Página</th><th>Factura detectada</th><th>Proveedor</th><th>Total</th><th>Confianza</th><th>Acciones</th></tr></thead><tbody>{visible.map((invoice) => <tr key={invoice.id}><td><span className={"badge " + tone(invoice.status)}>{invoice.status}</span></td><td>{invoice.fileName}</td><td>{invoice.sourcePageStart === invoice.sourcePageEnd ? invoice.sourcePageStart : `${invoice.sourcePageStart ?? "—"}-${invoice.sourcePageEnd ?? "—"}`}</td><td className="strong">{invoice.invoiceNumber.normalizedValue || "—"}<small className="sub">{invoice.date.normalizedValue || "—"} · {invoice.sourceType}</small></td><td>{invoice.supplier.normalizedValue || "—"}</td><td className="strong">{invoice.total.normalizedValue == null ? "—" : money(invoice.total.normalizedValue)}</td><td><span className={"confidence " + tone(invoice.confidence)}>{invoice.confidence}</span></td><td><div className="row-actions"><button title="Ver" onClick={() => setSelected(invoice)}><Eye/></button><button title="Editar" onClick={() => setSelected(invoice)}><Pencil/></button><button title="Reprocesar documento" onClick={() => retry(invoice)}><RotateCcw/></button><button title="Eliminar" onClick={() => setInvoices((current) => current.filter((entry) => entry.id !== invoice.id))}><Trash2/></button></div></td></tr>)}</tbody></table></div>}
      <div className="inventory-prep"><PackageCheck/><span><b>Preparación para inventario</b>Revisa proveedor, factura, producto y cantidad antes de crear una futura entrada.</span><button className="secondary" disabled={!visible.some((invoice) => invoice.items.length)} onClick={() => notify("Resumen de entrada preparado; el inventario no fue modificado")}>Preparar entrada de inventario</button></div>
    </>}
    {selected && <InvoiceEditor invoice={selected} close={() => setSelected(null)} save={(invoice) => { update(invoice.id, invoice); setSelected(null); notify("Correcciones guardadas"); }}/>} 
  </div>;
}

function MiniKpi({ label, value, tone = "green" }: { label: string; value: string; tone?: string }) { return <article className={"invoice-mini-kpi " + tone}><span>{label}</span><b>{value}</b></article>; }

function InvoiceEditor({ invoice, close, save }: { invoice: Invoice; close: () => void; save: (invoice: Invoice) => void }) {
  const [draft, setDraft] = useState(invoice);
  const setText = (key: "invoiceNumber" | "date" | "supplier", value: string) => setDraft((current) => ({ ...current, [key]: { ...current[key], originalValue: value, normalizedValue: value, confidence: "Alta" as ConfidenceLevel } }));
  const setItem = (id: string, key: keyof Pick<InvoiceItem, "code" | "description" | "quantity" | "unitPrice" | "lineTotal">, value: string) => setDraft((current) => ({ ...current, items: current.items.map((item) => item.id === id ? { ...item, [key]: { ...item[key], originalValue: value, normalizedValue: key === "quantity" || key === "unitPrice" || key === "lineTotal" ? Number(value) : value, confidence: "Alta" } as ExtractionField<string | number> } : item) }));
  const finalize = () => save({ ...draft, status: "Completado", confidence: "Alta", issues: draft.issues.map((issue) => ({ ...issue, resolved: true })) });
  return <div className="modal-bg"><div className="modal invoice-editor"><button className="modal-x" onClick={close}><X/></button><span className="eyebrow">REVISIÓN DE FACTURA</span><h2>{draft.invoiceNumber.normalizedValue || draft.fileName}</h2><p>{draft.fileName} · {draft.pageCount} página(s) · extracción por {draft.sourceType}</p><div className="editor-fields"><label>Número de factura<input value={draft.invoiceNumber.normalizedValue ?? ""} onChange={(event) => setText("invoiceNumber", event.target.value)}/></label><label>Fecha<input type="date" value={draft.date.normalizedValue ?? ""} onChange={(event) => setText("date", event.target.value)}/></label><label>Proveedor<input value={draft.supplier.normalizedValue ?? ""} onChange={(event) => setText("supplier", event.target.value)}/></label><label>Total<input type="number" value={draft.total.normalizedValue ?? ""} onChange={(event) => setDraft((current) => ({ ...current, total: { ...current.total, normalizedValue: Number(event.target.value), originalValue: event.target.value, confidence: "Alta" } }))}/></label></div>
    {draft.deliveryNumber?.normalizedValue && <p><b>Entrega:</b> {draft.deliveryNumber.normalizedValue}</p>}<h3>Productos</h3><div className="table-wrap"><table><thead><tr><th>Código</th><th>Descripción</th><th>Cantidad</th><th>Precio</th><th>Total</th></tr></thead><tbody>{draft.items.map((item) => <tr key={item.id}><td><input value={item.code.normalizedValue ?? ""} onChange={(event) => setItem(item.id, "code", event.target.value)}/></td><td><input value={item.description.normalizedValue ?? ""} onChange={(event) => setItem(item.id, "description", event.target.value)}/></td><td><input type="number" value={item.quantity.normalizedValue ?? ""} onChange={(event) => setItem(item.id, "quantity", event.target.value)}/></td><td><input type="number" value={item.unitPrice.normalizedValue ?? ""} onChange={(event) => setItem(item.id, "unitPrice", event.target.value)}/></td><td><input type="number" value={item.lineTotal.normalizedValue ?? ""} onChange={(event) => setItem(item.id, "lineTotal", event.target.value)}/></td></tr>)}</tbody></table></div>
    {draft.issues.length > 0 && <div className="editor-issues"><AlertTriangle/><span><b>{draft.issues.filter((issue) => !issue.resolved).length} observaciones</b>{draft.issues.map((issue) => <small key={issue.id}>{issue.problem}</small>)}</span></div>}
    <div className="modal-actions"><button className="secondary" onClick={close}>Cancelar</button><button className="primary" onClick={finalize}><Check size={16}/> Guardar revisión</button></div></div></div>;
}
