import type { Invoice } from "../invoices/types";
import { reconcileDeliveries, reconciliationSummary } from "../invoices/reconcile";

const val = <T,>(entry: { normalizedValue: T | null }) => entry.normalizedValue ?? "";
const text = (value: unknown) => value == null ? "" : String(value);
const sourcePage = (invoice: Invoice) => invoice.sourcePageStart == null ? "" : invoice.sourcePageStart === invoice.sourcePageEnd || invoice.sourcePageEnd == null ? invoice.sourcePageStart : `${invoice.sourcePageStart}-${invoice.sourcePageEnd}`;

export async function createInvoiceWorkbook(invoices: Invoice[]) {
  const XLSX = await import("xlsx");
  const reconciliation = reconcileDeliveries(invoices); const reconciliationKpis = reconciliationSummary(reconciliation);
  const completed = invoices.filter((invoice) => invoice.status !== "Pendiente" && invoice.status !== "Procesando" && invoice.documentType !== "delivery_note");
  const deliveryNotes = invoices.filter((invoice) => invoice.documentType === "delivery_note");
  const products = completed.flatMap((invoice) => invoice.items.map((item) => ({
    "Archivo origen": invoice.fileName, "Página origen": sourcePage(invoice), Fecha: text(val(invoice.date)), Factura: text(val(invoice.invoiceNumber)), Proveedor: text(val(invoice.supplier)), "Identificación proveedor": text(val(invoice.supplierId)),
    Código: text(val(item.code)), Descripción: text(val(item.description)), CABYS: text(item.cabys), Lote: text(item.lot), Cantidad: val(item.quantity), Unidad: text(val(item.unit)),
    "Peso bruto": item.grossWeight ?? "", "Peso neto": item.netWeight ?? "", "Precio unitario": val(item.unitPrice), Descuento: val(item.discount), Impuesto: val(item.tax), "Total línea": val(item.lineTotal),
  })));
  const consolidated = new Map<string, { code: string; product: string; quantity: number; cost: number; invoices: Set<string>; suppliers: Set<string> }>();
  for (const row of products) { const key = String(row.Código || row.Descripción).trim().toLowerCase(); if (!key) continue; const current = consolidated.get(key) ?? { code: row.Código, product: row.Descripción, quantity: 0, cost: 0, invoices: new Set(), suppliers: new Set() }; current.quantity += Number(row.Cantidad) || 0; current.cost += Number(row["Total línea"]) || 0; current.invoices.add(row.Factura); current.suppliers.add(row.Proveedor); consolidated.set(key, current); }
  const suppliers = new Map<string, { invoices: Set<string>; total: number; products: Set<string>; units: number }>();
  for (const invoice of completed) { const supplier = text(val(invoice.supplier) || "Sin identificar"); const current = suppliers.get(supplier) ?? { invoices: new Set(), total: 0, products: new Set(), units: 0 }; current.invoices.add(text(val(invoice.invoiceNumber) || invoice.fileName)); current.total += Number(val(invoice.total)) || 0; for (const item of invoice.items) { current.products.add(text(val(item.code) || val(item.description))); current.units += Number(val(item.quantity)) || 0; } suppliers.set(supplier, current); }
  const workbook = XLSX.utils.book_new();
  const add = (name: string, rows: Record<string, unknown>[], textColumns: string[] = []) => { const sheet = XLSX.utils.json_to_sheet(rows); const headers = rows.length ? Object.keys(rows[0]) : []; for (const columnName of textColumns) { const column = headers.indexOf(columnName); if (column < 0) continue; for (let row = 1; row <= rows.length; row += 1) { const address = XLSX.utils.encode_cell({ r: row, c: column }); if (sheet[address]) { sheet[address].t = "s"; sheet[address].v = text(sheet[address].v); sheet[address].z = "@"; } } } sheet["!cols"] = headers.map((header) => ({ wch: Math.max(14, Math.min(32, header.length + 8)) })); XLSX.utils.book_append_sheet(workbook, sheet, name); };
  const totalPurchases = completed.reduce((sum, invoice) => sum + (Number(val(invoice.total)) || 0), 0); const totalUnits = products.reduce((sum, row) => sum + (Number(row.Cantidad) || 0), 0);
  add("Resumen", [{ Periodo: "Lote actual", Facturas: completed.length, "Notas de entrega": deliveryNotes.length, Coincidencias: reconciliationKpis.matches, "Facturas sin nota": reconciliationKpis.invoicesWithoutNote, "Notas sin factura": reconciliationKpis.notesWithoutInvoice, Duplicados: reconciliationKpis.duplicates, Revisión: reconciliationKpis.review, "% conciliación": reconciliationKpis.percentage, "Total compras": totalPurchases, "Total productos": products.length, "Total unidades": totalUnits, "Total proveedores": suppliers.size }]);
  add("Facturas", completed.map((invoice) => ({ "Archivo origen": invoice.fileName, "Página origen": sourcePage(invoice), "Tipo documento": text(invoice.documentTypeLabel ? val(invoice.documentTypeLabel) : "Factura"), Factura: text(val(invoice.invoiceNumber)), Fecha: text(val(invoice.date)), Proveedor: text(val(invoice.supplier)), "Identificación proveedor": text(val(invoice.supplierId)), Cliente: text(invoice.client ? val(invoice.client) : ""), "Identificación cliente": text(invoice.clientId ? val(invoice.clientId) : ""), "Doc. Interno": text(invoice.internalDocument ? val(invoice.internalDocument) : ""), Pedido: text(invoice.orderNumber ? val(invoice.orderNumber) : ""), Entrega: text(invoice.deliveryNumber ? val(invoice.deliveryNumber) : ""), "Orden de compra": text(val(invoice.purchaseOrder)), Moneda: text(val(invoice.currency)), "Tipo de cambio": invoice.exchangeRate ? val(invoice.exchangeRate) : "", Incoterm: text(invoice.incoterm ? val(invoice.incoterm) : ""), "Peso bruto total": invoice.totalGrossWeight ? val(invoice.totalGrossWeight) : "", "Peso neto total": invoice.totalNetWeight ? val(invoice.totalNetWeight) : "", Subtotal: val(invoice.subtotal), "Total gravado": invoice.taxableTotal ? val(invoice.taxableTotal) : "", "Total exento": invoice.exemptTotal ? val(invoice.exemptTotal) : "", "Total exonerado": invoice.exoneratedTotal ? val(invoice.exoneratedTotal) : "", Impuesto: val(invoice.tax), "Total comprobante": val(invoice.total), Estado: invoice.status, Confianza: invoice.confidence })), ["Factura", "Identificación proveedor", "Identificación cliente", "Doc. Interno", "Pedido", "Entrega", "Orden de compra"]);
  add("Productos", products, ["Factura", "Identificación proveedor", "Código", "CABYS", "Lote"]);
  add("Notas de Entrega", deliveryNotes.map((note) => ({ "Archivo origen": note.fileName, "Página origen": sourcePage(note), "Número entrega": text(note.deliveryNumber ? val(note.deliveryNumber) : ""), Fecha: text(val(note.date)), Pedido: text(note.orderNumber ? val(note.orderNumber) : ""), "Orden compra": text(val(note.purchaseOrder)), Cliente: text(note.client ? val(note.client) : ""), Estado: note.status, Confianza: note.confidence })), ["Número entrega", "Pedido", "Orden compra"]);
  add("Productos Entregados", deliveryNotes.flatMap((note) => note.items.map((item) => ({ "Archivo origen": note.fileName, "Página origen": sourcePage(note), Entrega: text(note.deliveryNumber ? val(note.deliveryNumber) : ""), Código: text(val(item.code)), Descripción: text(val(item.description)), Cantidad: val(item.quantity), "Peso bruto": item.grossWeight ?? "", "Peso neto": item.netWeight ?? "" }))), ["Entrega", "Código"]);
  const reconciliationRows = reconciliation.map((record) => { const invoice = record.invoices[0]; const note = record.deliveryNotes[0]; return { Entrega: record.deliveryNumber, Factura: invoice ? text(val(invoice.invoiceNumber)) : "", "Fecha factura": invoice ? text(val(invoice.date)) : "", Proveedor: invoice ? text(val(invoice.supplier)) : "", "Total factura": invoice ? val(invoice.total) : "", "Nota entrega": note ? text(note.deliveryNumber ? val(note.deliveryNumber) : "") : "", "Fecha entrega": note ? text(val(note.date)) : "", "Pedido factura": invoice?.orderNumber ? text(val(invoice.orderNumber)) : "", "Pedido nota": note?.orderNumber ? text(val(note.orderNumber)) : "", "Orden compra": invoice ? text(val(invoice.purchaseOrder)) : note ? text(val(note.purchaseOrder)) : "", "Estado conciliación": record.status, Observación: record.observation, "Archivo factura": invoice?.fileName ?? "", "Página factura": invoice ? sourcePage(invoice) : "", "Archivo nota": note?.fileName ?? "", "Página nota": note ? sourcePage(note) : "" }; });
  add("Conciliación Entregas", reconciliationRows, ["Entrega", "Factura", "Nota entrega", "Pedido factura", "Pedido nota", "Orden compra"]);
  add("Facturas sin Nota", reconciliationRows.filter((row) => row["Estado conciliación"] === "Factura sin nota"), ["Entrega", "Factura", "Pedido factura", "Orden compra"]);
  add("Notas sin Factura", reconciliationRows.filter((row) => row["Estado conciliación"] === "Nota sin factura"), ["Entrega", "Nota entrega", "Pedido nota"]);
  add("Productos Consolidados", [...consolidated.values()].map((row) => ({ Código: text(row.code), Producto: row.product, "Cantidad total": row.quantity, "Costo total": row.cost, "Costo promedio": row.quantity ? row.cost / row.quantity : 0, "Número de facturas": row.invoices.size, "Número de proveedores": row.suppliers.size })), ["Código"]);
  add("Proveedores", [...suppliers.entries()].map(([supplier, row]) => ({ Proveedor: supplier, "Cantidad de facturas": row.invoices.size, "Total comprado": row.total, "Productos diferentes": row.products.size, "Unidades compradas": row.units })));
  add("Revisión", completed.flatMap((invoice) => invoice.issues.map((issue) => ({ "Archivo origen": invoice.fileName, "Página origen": sourcePage(invoice), Factura: text(val(invoice.invoiceNumber) || invoice.fileName), Campo: issue.field, Valor: text(issue.value), Problema: issue.problem, Confianza: issue.confidence, Estado: issue.resolved ? "Resuelto" : "Pendiente" }))), ["Factura", "Valor"]);
  return workbook;
}

export async function exportInvoiceWorkbook(invoices: Invoice[]) {
  const XLSX = await import("xlsx"); const workbook = await createInvoiceWorkbook(invoices);
  XLSX.writeFile(workbook, "SYNERA_Invoice_Analysis.xlsx", { compression: true });
}
